### ISSUE TITLE
example doesn't work in godot 4

### ISSUE THREAD

**Issue by eddex** [Beebster-UK/Godot-Player-Vignette-Shader-Example#1]
I'm trying to get this project to run in godot 4. However, the position of the player is not updated.
Do you have any clue how I can do this?

To get the shader working I had to change `hint_color` to `source_color`:
```gdshader
shader_type canvas_item;
uniform vec2 player_position;
uniform vec4 color : source_color = vec4(0.305, 0.298, 0.341,1);

uniform float MULTIPLIER = 0.56;
uniform float SCALE = 0.5;
uniform float SOFTNESS = 0.65;


float circle(vec2 position, float radius, float feather)
{
	return smoothstep(radius, radius + feather, dot(position, position ) * 8.0);
}

float vigTypeB(vec2 dude){
	float vignette = circle(dude - vec2(player_position.x,player_position.y ), 0.1, 0.5);
	return vignette;
}

float vigTypeA(vec2 dude){
	float val = distance(vec2(dude.x , dude.y * MULTIPLIER), vec2(player_position.x , player_position.y * MULTIPLIER));
	val = val / SCALE;
	float vignette = smoothstep(0.2, SOFTNESS, val);
	return vignette;
}

void fragment(){
	COLOR = vec4(color.rgb , vigTypeA(UV));
}
```

When I start the project, it looks like this:
![image](https://user-images.githubusercontent.com/5302085/226451938-70933e30-1101-4a89-ab83-ab1376dcbd15.png)

**Comment by eddex** [comment]
Found the issue:

In `Player.gd`, we get the `screen_dimensions`. `get_viewport().size` returns a `Vector2i` (a vector of integers).
We need to convert this to a `Vector2` to allow for floating point numbers.

The calculation of the `player_position_uv` needs to be changes like this:
`player_position_uv = global_position / Vector2(screen_dimensions)`

**Comment by Beebster-UK** [comment]
Hi Marco,
                Thanks for reminding me. I've recreated the same example in
Godot 4 and published to GitHub.

https://github.com/Beebster-UK/Godot4-Player-Vignette-Shader-Example

Kind Regards,

Ian

**Comment by eddex** [comment]
Awesome! Thanks for publishing the updated project. I was thinking about creating a PR here to update it, but it makes sense to also keep the 3.x version. 👍
